name: Deploy to EC2 via GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        install -m 700 -d ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/SourceCode/GithubActionTest
          echo "========== $(date) ==========" >> deploy.log
          git pull origin main >> deploy.log 2>&1
          source venv/bin/activate >> deploy.log 2>&1
          pip install -r requirements.txt >> deploy.log 2>&1
          echo "Service Started : App.py" >> deploy.log
        EOF